const a = {
    "lazyLoad": false,
    "isVisual": false,
    "services_search": true,
    "services": {
        "1": {
            "id": "1",
            "cid": "1",
            "position": "1",
            "type": "0",
            "price": "1000",
            "favorite": false,
            "added_to_favorite_at": null,
            "orig_price": 1000,
            "link_type": "0",
            "description": null,
            "min": "1",
            "max": "10000",
            "min_max_label": "최소: 1 - 최대: 10000",
            "average_time": "데이터가 충분하지 않습니다",
            "origin_name": "유튜브 상품1",
            "name": "1 - 유튜브 상품1",
            "name_template": {
                "search_template": "{{service_id}} - {{service_name}}",
                "template": "{{service_id}} {{service_name}}",
                "service_name": "유튜브 상품1",
                "service_id": "1",
                "rate_formatted": "",
            },
        },
        "3": {
            "id": "3",
            "cid": "2",
            "position": "1",
            "type": "0",
            "price": "1",
            "favorite": false,
            "added_to_favorite_at": null,
            "orig_price": 1,
            "link_type": "0",
            "description": null,
            "min": "1",
            "max": "1",
            "min_max_label": "최소: 1 - 최대: 1",
            "average_time": "데이터가 충분하지 않습니다",
            "origin_name": "인스타그램 상품1",
            "name": "3 - 인스타그램 상품1",
            "name_template": {
                "search_template": "{{service_id}} - {{service_name}}",
                "template": "{{service_id}} {{service_name}}",
                "service_name": "인스타그램 상품1",
                "service_id": "3",
                "rate_formatted": "",
            },
        },
        "4": {
            "id": "4",
            "cid": "3",
            "position": "1",
            "type": "0",
            "price": "1",
            "favorite": false,
            "added_to_favorite_at": null,
            "orig_price": 1,
            "link_type": "0",
            "description": null,
            "min": "1",
            "max": "111",
            "min_max_label": "최소: 1 - 최대: 111",
            "average_time": "데이터가 충분하지 않습니다",
            "origin_name": "페이스북 상품1",
            "name": "4 - 페이스북 상품1",
            "name_template": {
                "search_template": "{{service_id}} - {{service_name}}",
                "template": "{{service_id}} {{service_name}}",
                "service_name": "페이스북 상품1",
                "service_id": "4",
                "rate_formatted": "",
            },
        },
        "5": {
            "id": "5",
            "cid": "4",
            "position": "1",
            "type": "0",
            "price": "1424",
            "favorite": false,
            "added_to_favorite_at": null,
            "orig_price": 1424,
            "link_type": "0",
            "description": null,
            "min": "11",
            "max": "3234",
            "min_max_label": "최소: 11 - 최대: 3234",
            "average_time": "데이터가 충분하지 않습니다",
            "origin_name": "스레드",
            "name": "5 - 스레드",
            "name_template": {
                "search_template": "{{service_id}} - {{service_name}}",
                "template": "{{service_id}} {{service_name}}",
                "service_name": "스레드",
                "service_id": "5",
                "rate_formatted": "",
            },
        },
        "6": {
            "id": "6",
            "cid": "0",
            "position": "1",
            "type": "100",
            "price": "1000",
            "favorite": false,
            "added_to_favorite_at": null,
            "orig_price": 1000,
            "link_type": "7",
            "description": null,
            "min": "100",
            "max": "100000",
            "min_max_label": "최소: 100 - 최대: 100000",
            "average_time": "데이터가 충분하지 않습니다",
            "origin_name": "subscription test",
            "name": "6 - subscription test",
            "name_template": {
                "search_template": "{{service_id}} - {{service_name}}",
                "template": "{{service_id}} {{service_name}}",
                "service_name": "subscription test",
                "service_id": "6",
                "rate_formatted": "",
            },
        },
        "2": {
            "id": "2",
            "cid": "1",
            "position": "2",
            "type": "0",
            "price": "10000",
            "favorite": false,
            "added_to_favorite_at": null,
            "orig_price": 10000,
            "link_type": "0",
            "description": null,
            "min": "1",
            "max": "34245",
            "min_max_label": "최소: 1 - 최대: 34245",
            "average_time": "데이터가 충분하지 않습니다",
            "origin_name": "유튜브 상품2",
            "name": "2 - 유튜브 상품2",
            "name_template": {
                "search_template": "{{service_id}} - {{service_name}}",
                "template": "{{service_id}} {{service_name}}",
                "service_name": "유튜브 상품2",
                "service_id": "2",
                "rate_formatted": "",
            },
        },
    },
    "fields": {
        "0": [
            {
                "field": "text",
                "name": "link",
                "label": "링크",
                "required": true,
                "type": "string",
            },
            {
                "field": "text",
                "name": "quantity",
                "label": "수량",
                "required": true,
                "type": "integer",
            },
            {
                "field": "text",
                "name": "average_time",
                "label": "평균 완료 시간",
                "disabled": true,
                "type": "string",
            },
        ],
        "1": [
            { "field": "text", "name": "link", "label": "링크" },
            { "field": "text", "name": "quantity", "label": "수량" },
            {
                "field": "textarea",
                "name": "keywords",
                "label": "키워드 (한 줄에 한 개)",
                "required": true,
            },
            {
                "field": "text",
                "name": "average_time",
                "label": "평균 완료 시간",
                "disabled": true,
                "type": "string",
            },
        ],
        "2": [
            { "field": "text", "name": "link", "label": "링크" },
            {
                "field": "text",
                "name": "quantity",
                "label": "수량",
                "disabled": true,
                "related": "comment",
            },
            { "field": "textarea", "name": "comment", "label": "댓글 (한 줄에 한 개)" },
            {
                "field": "text",
                "name": "average_time",
                "label": "평균 완료 시간",
                "disabled": true,
                "type": "string",
            },
        ],
        "9": [
            { "field": "text", "name": "link", "label": "링크" },
            { "field": "text", "name": "quantity", "label": "수량" },
            {
                "field": "textarea",
                "name": "mentionUsernames",
                "label": "아이디 (한 줄에 한 개)",
            },
            {
                "field": "text",
                "name": "average_time",
                "label": "평균 완료 시간",
                "disabled": true,
                "type": "string",
            },
        ],
        "3": [
            { "field": "text", "name": "link", "label": "링크" },
            { "field": "text", "name": "quantity", "label": "수량" },
            { "field": "textarea", "name": "usernames", "label": "아이디 (한 줄에 한 개)" },
            { "field": "textarea", "name": "hashtags", "label": "해시태그 (한 줄에 한 개)" },
            {
                "field": "text",
                "name": "average_time",
                "label": "평균 완료 시간",
                "disabled": true,
                "type": "string",
            },
        ],
        "4": [
            { "field": "text", "name": "link", "label": "링크" },
            {
                "field": "text",
                "name": "quantity",
                "label": "수량",
                "disabled": true,
                "related": "usernames_custom",
            },
            {
                "field": "textarea",
                "name": "usernames_custom",
                "label": "아이디 (한 줄에 한 개)",
            },
            {
                "field": "text",
                "name": "average_time",
                "label": "평균 완료 시간",
                "disabled": true,
                "type": "string",
            },
        ],
        "6": [
            { "field": "text", "name": "link", "label": "링크" },
            { "field": "text", "name": "quantity", "label": "수량" },
            { "field": "text", "name": "hashtag", "label": "해시태그" },
            {
                "field": "text",
                "name": "average_time",
                "label": "평균 완료 시간",
                "disabled": true,
                "type": "string",
            },
        ],
        "7": [
            { "field": "text", "name": "link", "label": "링크" },
            { "field": "text", "name": "quantity", "label": "수량" },
            { "field": "text", "name": "username", "label": "아이디" },
            {
                "field": "text",
                "name": "average_time",
                "label": "평균 완료 시간",
                "disabled": true,
                "type": "string",
            },
        ],
        "8": [
            { "field": "text", "name": "link", "label": "링크" },
            { "field": "text", "name": "quantity", "label": "수량" },
            { "field": "text", "name": "mediaUrl", "label": "미디어 URL" },
            {
                "field": "text",
                "name": "average_time",
                "label": "평균 완료 시간",
                "disabled": true,
                "type": "string",
            },
        ],
        "10": [
            { "field": "text", "name": "link", "label": "링크" },
            {
                "field": "text",
                "name": "average_time",
                "label": "평균 완료 시간",
                "disabled": true,
                "type": "string",
            },
        ],
        "12": [
            { "field": "text", "name": "link", "label": "링크" },
            { "field": "text", "name": "quantity", "label": "수량" },
            { "field": "checkbox", "name": "check", "label": "반복 주문" },
            { "field": "text", "name": "runs", "label": "neworder.runs" },
            { "field": "text", "name": "interval", "label": "neworder.interval" },
            {
                "field": "text",
                "name": "average_time",
                "label": "평균 완료 시간",
                "disabled": true,
                "type": "string",
            },
        ],
        "14": [
            { "field": "text", "name": "link", "label": "링크" },
            { "field": "textarea", "name": "comment", "label": "댓글 (한 줄에 한 개)" },
            {
                "field": "text",
                "name": "average_time",
                "label": "평균 완료 시간",
                "disabled": true,
                "type": "string",
            },
        ],
        "100": [
            { "field": "text", "name": "username", "label": "아이디" },
            { "field": "text", "name": "posts", "label": "새 게시물" },
            { "field": "text", "name": "old_posts", "label": "Old posts" },
            { "field": "text", "name": "min", "label": "수량" },
            { "field": "text", "name": "max", "label": "수량" },
            { "field": "text", "name": "delay", "label": "지연시간" },
            { "field": "text", "name": "expiry", "label": "종료날짜" },
            {
                "field": "text",
                "name": "average_time",
                "label": "평균 완료 시간",
                "disabled": true,
                "type": "string",
            },
        ],
        "15": [
            { "field": "text", "name": "link", "label": "링크" },
            { "field": "text", "name": "quantity", "label": "수량" },
            { "field": "text", "name": "comment_username", "label": "댓글 작성자의 아이디" },
            {
                "field": "text",
                "name": "average_time",
                "label": "평균 완료 시간",
                "disabled": true,
                "type": "string",
            },
        ],
        "16": [
            { "field": "text", "name": "link", "label": "링크" },
            {
                "field": "textarea",
                "name": "keywords",
                "label": "키워드 (한 줄에 한 개)",
                "required": true,
            },
            {
                "field": "text",
                "name": "average_time",
                "label": "평균 완료 시간",
                "disabled": true,
                "type": "string",
            },
        ],
        "17": [
            {
                "field": "text",
                "name": "link",
                "label": "링크",
                "required": true,
                "type": "string",
            },
            {
                "field": "text",
                "name": "quantity",
                "label": "수량",
                "required": true,
                "type": "integer",
            },
            { "field": "text", "name": "answer_number", "label": "답변수" },
            {
                "field": "text",
                "name": "average_time",
                "label": "평균 완료 시간",
                "disabled": true,
                "type": "string",
            },
        ],
        "18": [
            { "field": "text", "name": "username", "label": "아이디" },
            { "field": "text", "name": "link", "label": "링크" },
            {
                "field": "text",
                "name": "quantity",
                "label": "수량",
                "disabled": true,
                "related": "comment",
            },
            { "field": "textarea", "name": "comment", "label": "댓글 (한 줄에 한 개)" },
            {
                "field": "text",
                "name": "average_time",
                "label": "평균 완료 시간",
                "disabled": true,
                "type": "string",
            },
        ],
        "19": [
            { "field": "text", "name": "link", "label": "링크" },
            { "field": "text", "name": "quantity", "label": "수량" },
            {
                "field": "textarea",
                "name": "keywords",
                "label": "키워드 (한 줄에 한 개)",
                "required": true,
            },
            { "field": "text", "name": "email", "label": "이메일" },
            {
                "field": "text",
                "name": "average_time",
                "label": "평균 완료 시간",
                "disabled": true,
                "type": "string",
            },
        ],
        "20": [
            { "field": "text", "name": "link", "label": "링크" },
            { "field": "text", "name": "quantity", "label": "수량" },
            { "field": "textarea", "name": "groups", "label": "그룹", "required": true },
            {
                "field": "text",
                "name": "average_time",
                "label": "평균 완료 시간",
                "disabled": true,
                "type": "string",
            },
        ],
    },
    "currency": {
        "template": "₩{{value}}",
        "original_template": "₩{{value}}",
        "converted": false,
    },
    "constants": { "old_posts_max_quantity": null },
    "format": {
        "min_price": 0.0001,
        "max": 7,
        "min": 0,
        "delimiter": ".",
        "thousands": ",",
    },
    "fieldOptions": {
        "fields": [
            "user_name",
            "link",
            "quantity",
            "keywords",
            "comment",
            "mention_usernames",
            "usernames",
            "usernames_custom",
            "username",
            "media_url",
            "hashtag",
            "hashtags",
            "dripfeed",
            "posts",
            "old_posts",
            "min",
            "delay",
            "expiry",
            "comment_username",
            "answer_number",
            "email",
            "groups",
        ],
        "data": {
            "order_id": null,
            "category": 1,
            "service": null,
            "termsofservice": null,
            "max": null,
            "min": null,
            "posts": null,
            "old_posts": null,
            "interval": null,
            "runs": null,
            "delay": null,
            "check": null,
            "hashtag": null,
            "hashtags": null,
            "description": null,
            "mediaUrl": null,
            "topic": null,
            "username": null,
            "usernames_custom": null,
            "usernames": null,
            "mentionUsernames": null,
            "comment": null,
            "keywords": null,
            "quantity": null,
            "link": null,
            "password": null,
            "user_name": null,
            "expiry": null,
            "total_quantity": null,
            "comment_username": null,
            "answer_number": null,
            "email": null,
            "groups": null,
            "fields": [
                "max",
                "min",
                "posts",
                "old_posts",
                "interval",
                "runs",
                "check",
                "hashtag",
                "expiry",
                "description",
                "mediaUrl",
                "topic",
                "username",
                "usernames_custom",
                "usernames",
                "hashtags",
                "mentionUsernames",
                "comment",
                "keywords",
                "quantity",
                "link",
                "password",
                "user_name",
                "delay",
                "total_quantity",
                "comment_username",
                "answer_number",
                "email",
                "groups",
            ],
        },
        "label": {
            "delay": "지연시간",
            "username": "아이디",
            "channel_id": "채널 번호",
            "link": "링크",
            "quantity": "수량",
            "keywords": "키워드 (한 줄에 한 개)",
            "comments": "댓글 (한 줄에 한 개)",
            "usernames": "아이디 (한 줄에 한 개)",
            "mediaurl": "미디어 URL",
            "hashtag": "해시태그",
            "hashtags": "해시태그 (한 줄에 한 개)",
            "dripfeed": "반복 주문",
            "dripfeed.runs": "반복 횟수",
            "dripfeed.interval": "반복 간격 (분)",
            "dripfeed.total.quantity": "총 수량",
            "new_posts": "새 게시물",
            "old_posts": "Old posts",
            "max_count_old_posts": null,
            "min": "최소",
            "max": "최대",
            "expiry": "종료날짜",
            "comment_username": "댓글 작성자의 아이디",
            "answer_number": "답변수",
            "email": "이메일",
            "groups": "그룹",
            "average_time": "평균 완료 시간",
        },
        "delays": {
            "0": "지연 없음",
            "300": "5 분",
            "600": "10 분",
            "900": "15 분",
            "1800": "30 분",
            "3600": "60 분",
            "5400": "90 분",
            "7200": "120 분",
            "9000": "150 분",
            "10800": "180 분",
            "12600": "210 분",
            "14400": "240 분",
            "16200": "270 분",
            "18000": "300 분",
            "21600": "360 분",
            "25200": "420 분",
            "28800": "480 분",
            "32400": "540 분",
            "36000": "600 분",
        },
        "tooltips": { "average_time": "평균 완료 시간은 1000개당 최근 완료된 10개를 기준으로 합니다." },
    },
}
